//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Net_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBAT
    {
        public int id { get; set; }
        public string nama_obat { get; set; }
        public string jenis_obat { get; set; }
        public string harga_obat { get; set; }
    }
}
